#!/usr/bin/env bash
./configure \
  --prefix=../sysroot \
  --syslibdir=../sysroot/lib \
  --target=wasm32 \
  --enable-wrapper=no \
  --disable-shared \
  CC="clang" \
  CFLAGS="--target=wasm32 -pthread" \
  CROSS_COMPILE=llvm-
