#!/usr/bin/env bash
./configure \
  --prefix=../sysroot \
  --syslibdir=../sysroot/lib \
  --target=wasm32 \
  --enable-wrapper=no \
  --disable-shared \
  CC="clang --target=wasm32" \
  CFLAGS="-pthread" \
  CROSS_COMPILE=llvm-
