#!/usr/bin/env bash
./configure \
  --prefix=../sysroot \
  --syslibdir=../sysroot/lib \
  --target=wasm32 \
  --enable-wrapper=no \
  --disable-shared \
  --disable-optimize \
  --enable-debug \
  CC="clang" \
  CFLAGS="--target=wasm32 -pthread -ftls-model=local-exec -O0 -fwasm-exceptions" \
  CROSS_COMPILE=llvm-
